version: "3"

services:
  service:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: hello_app:latest
    hostname: service
    ports:
      - "5000:5000"
  proxy:
    image: nginx:latest
    ports:
     - "8080:80"
     - "443:443"
    volumes:
      - ./conf/:/etc/nginx/conf.d

